---
- name: Ensuring config directory exists
  file:
    path: "{{ pihole_dnsmasq_configuration_path }}"
    state: directory
- name: Configuring DNSMasq static addresses
  template:
    src: static-addresses.j2
    dest: "{{ pihole_dnsmasq_configuration_path }}/static-addresses.conf"
  notify: Restart dnsmasq container
  when: dnsmasq_static_addresses is defined and dnsmasq_static_addresses != []

- name: Configuring additional conditional forwarders
  template:
    src: conditional-forwarders.j2
    dest: "{{ pihole_dnsmasq_configuration_path }}/conditional-forwarders.conf"
  notify: Restart dnsmasq container
  when: dnsmasq_conditional_forwarders is defined and dnsmasq_conditional_forwarders != [] 
